### ISSUE TITLE
states.AWAITING

### ISSUE THREAD

**Issue by monolithed** [KlonD90/node-tarantool-driver#11]
Строки вида

```
states.AWAITING1 <Buffer 82 00 ce 00> <Buffer 00 00 00 01 cf 00 ... >
states.AWAITING2 <Buffer 00 00 00 01 cf 00 00 00 00 00 00 01 ac  ... >
```

Начинают приходить в stdout на вставке 2621-элемента, который в моем случае является дубликатом (_Duplicate key exists in unique index 'primary' in space 'partners'_).

Повторяется на операциях `insert` и `replace`

**Comment by monolithed** [comment]
Хм. ошибка сама-собой ушла

**Comment by KlonD90** [comment]
Может от длины запроса зависит?

**Comment by monolithed** [comment]
Данные те же. 
Гугл тоже не нашел совпадений по этому выводу.
Попробую в следующий раз отдебажить через strace, [gai](https://www.npmjs.com/package/gai), [irhydra](http://mrale.ph/irhydra/2/).

**Comment by KlonD90** [comment]
@monolithed добавил options.log при создание, посмотри возможно попроще будет увидеть что не так.

**Comment by monolithed** [comment]
Ок, я тогда тикет закрываю, поскольку воспроизвести уже не получается.
