### ISSUE TITLE
msgpack implementation

### ISSUE THREAD

**Issue by arusakov** [KlonD90/node-tarantool-driver#16]
Maybe change msgpack5 to [msgpack-lite] (https://www.npmjs.com/package/msgpack-lite)?
[Benchmarks] (https://www.npmjs.com/package/msgpack-lite#benchmarks) are very good. The official http://msgpack.org/ site refers to msgpack-lite javascript implementation.

**Comment by KlonD90** [comment]
Ok i check it. Thx

**Comment by KlonD90** [comment]
@arusakov use it in new version

**Comment by KlonD90** [comment]
+ now you can use your implementation.
