### ISSUE TITLE
Поддержать операцию upsert 

### ISSUE THREAD

**Issue by monolithed** [KlonD90/node-tarantool-driver#3]
https://github.com/tarantool/tarantool/issues/905

**Comment by KlonD90** [comment]
А она разве уже есть?

**Comment by monolithed** [comment]
На будущее, чтобы не забыть :)

**Comment by monolithed** [comment]
Зарелизили!

**Comment by KlonD90** [comment]
Прикручу на этих выходных, а скорее всего даже раньше, во вторник среду.

**Comment by KlonD90** [comment]
@monolithed поддержка добавил
