### ISSUE TITLE
Поддержать операцию call

### ISSUE THREAD

**Issue by monolithed** [KlonD90/node-tarantool-driver#7]
Без вызова хранимых процедур драйвер практически бесполезен (

**Comment by rtsisyk** [comment]
+1

**Comment by KlonD90** [comment]
Оно работает, я просто тесты на это не писал пока. Ну во всяком случае truncate отрабатывает.

**Comment by monolithed** [comment]
```lua
space:create_index('primary', {
	parts = {
		1, 'str'
	}
})

-- Хранимая процедура добавления списка записей
function batch (data)
	for index, value in pairs(data) do
		box.space[config.name]:insert(value)
	end
end
```

```js
tarantool.insert('batch', [
	[ 'foo' ], 
	[ 'bar' ],
])
.then(result => {
	console.log('result', result);
})
.catch(error => {
	console.log('error', error);
});
```

```
error Tuple/Key must be MsgPack array
```

Оказалось что в процедуру приходит первый элемент массива. 
Вот этот код отработает:

```lua
function batch (data)
	box.space[config.name]:insert(data)
end
``

Однако на сколько я ожидаю что в функцию должна прийти таблица элементов.
Я могу конечно передать json, предварительно сериализировать его у себе, а затем сделать декод в тарантуле, но это какой-то оверхед

**Comment by KlonD90** [comment]
@monolithed переделал немного call, чтобы он аргументы в себя принимал, а не просто массив. Нет там ничего не надо перекодировать и докодировать в том примере можно просто первый массив еще раз в массив обернуть, но в принципе в новой версии и так заработает, второй элемент массива просто становился вторым аргументом.

**Comment by KlonD90** [comment]
335b242b67d7224f24f9ad34b59b068a890e7b8b

**Comment by KlonD90** [comment]
@monolithed обнови package у себя должно заработать.

**Comment by monolithed** [comment]
Спасибо, сегодня попробую!
