### ISSUE TITLE
Конфликт индексов

### ISSUE THREAD

**Issue by monolithed** [KlonD90/node-tarantool-driver#9]
В Lua индексы начинаются с 1 и в тарантуле тоже. 
Я правильно понимаю, что нумерация индексов в `select` начинаются с 0 и почему?

**Comment by KlonD90** [comment]
Там требуется id, или нужна автоподстановка/автокоррекция какая-то?

**Comment by monolithed** [comment]
```lua
space = box.schema.space.create('test', {
	temporary = true
})

space:create_index('primary', {
   parts = {
         0, 'str', 
   }
})

-- 2015-07-24 13:43:38.118 [34003] main/101/index.lua F> Illegal parameters, invalid index parts: field_no must be one-based
```

```lua
space:create_index('primary', {
   parts = {
         1, 'str'
   }
})

space:insert {1};
space:select {1}; -- [1]
```

```js
tarantool.insert(space_id, ['test']);
tarantool.select(space_id, 0, 0xffffffff, 0, 'eq', ['test']); // ['one' ]
```


С другой стороны

```lua
---
- unique: true
  parts:
  - type: STR
    fieldno: 1
  id: 0
  space_id: 514
  name: primary
  type: TREE
...
```

`id` действительно нулевой и типо все логично.  :)

**Comment by KlonD90** [comment]
Это не id индекса там, а номер поля, типа создать индекс для первого поля. А вот id индекса это как раз то что потом выводится.

**Comment by monolithed** [comment]
Ага, это видимо у меня какой-то диссонанс, в 1,5 можно было в конфиге создавать поля с нуля)
